- week2/1914.py
- 문제 번호: 1914
- 재귀 함수 활용
- 목표 원판N을 옮기기 위해 N-1개의 원판을 옮기는 재귀적 호출 방식으로 구현
- 시간복잡도: O(2^n)
- 공간복잡도: O(n)
- 간략한 코드
> [1914] 09.05 이지원

- week3/17413.py
- week4/1158.py
- 문제 번호: 1158
- 큐를 활용하여 해결
- pop을 사용하여 +K번째 사람을 뽑음
- 공간복잡도: O(N)
- while문을 사용하지 않고 for문을 사용함
> [1158] 09.30 안수연

- week4/24060.py
- 문제 번호: 24060
- 배열을 슬라이싱 하지 않고, 원래의 인덱스를 유지하면서 정렬하는 병합 정렬 사용 (재귀 호출 가능)
- 글로벌 count를 설정하여 저장하는 횟수를 카운팅하며 정답을 찾아가는 것
- 시간복잡도: O(N log N) (병합 정렬의 기본 시간 복잡도)
- 공간복잡도: O(N) (병합 과정에서 임시 배열 사용)
- 다른 코드들과 비교했을 때 이 코드의 장점은 무엇인가요? 주석 처리가 잘 되어 있음
> 24060 jiwon

- week5/11724.py
- week5/9461.py
- 문제 번호: 9461
- P(n) = P(n-2) + P(n-3) (n>=4) 수식 세우기
- 다이나믹 프로그래밍: 파도반 수열을 미리 계산하여 저장해놓기
- 시간복잡도: O(T)
- 공간복잡도: O(100)
- 미리 계산된 값을 사용하기 때문에 테스트 케이스가 많아도 빠르게 작동한다.
> [9461] 10.08 김지현

- week5/2493.py
- 문제 번호: 2493
- 스택에 탑의 높이 값이 아닌 인덱스를 저장하여 따로 인덱스를 찾지 않도록 하여 시간복잡도 감소
- 스택의 최상단의 기둥이 신호를 수신하게 됨
- 시간복잡도: O(N)
- 공간복잡도: O(N)
- 탑의 높이는 저장하지 않고 인덱스만 저장하여 메모리 절약
> 2493 jiwon

- week5/2493.py
- week5/2981.py
- week6/17298.py
- 문제 번호: 17298
- 시간복잡도: O(N)
- 공간복잡도: O(N)
- 스택에 인덱스를 저장해서 비교하면 시간 복잡도를 효율적으로 줄일 수 있다.
> [17298] 10.14 김지현

- week6/17298.py
- week6/5397.py
- 문제 번호: 5397
- 커서를 기준으로 왼쪽과 오른쪽 리스트로 나눔
- 커서가 오른쪽에서 왼쪽으로 이동할 때는 왼쪽 리스트에서 pop()하고 appendleft()로 오른쪽 리스트에 추가
- 커서가 왼쪽에서 오른쪽으로 이동할 때는 오른쪽 리스트에서 popleft()하고 append()로 왼쪽 리스트에 추가
- 시간복잡도: O(N)
- 공간복잡도: O(N)
> [5397] 10.15 안수연 deque

- week7/1283.py
- week7/2075.py
- 문제 번호: 1283
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 
단어의 첫번째를 키로 사용할 수 있는지 먼저 확인해야해서 for문을 여러번 돌아야함 for문을 여러번 도는 것을 최소화하기 위해서 bool 변수가 하나 필요
- 시간복잡도: O(n * m * l)
- 공간복잡도: O(n * m)
- 코드 리뷰어가 참고해야 할 사항이나 질문이 있다면 작성해 주세요: 아무리봐도 이 코드 좀 더러워
> [1283] 10.24 오세영

- week7/19637.py
- week8/1522.py
- week8/2178.py
- 문제 번호: 1522
- 전체 a의 개수를 window의 크기로 지정
- 교환해야하는 횟수는 전체 a의 개수에서 window에 있는 a의 개수를 뺀 것
- window에 있는 a의 개수를 확인할 때는 일일이 다시 count하는 것이 아니라 나가고 들어오는 것만 확인해서 더하고 빼면 됨
- 시간복잡도: O(N)
- 공간복잡도: O(N)
- window 사용
> [1522] 10.28 안수연

- week9/14425.py
- week9/9017.py
- 문제 번호: 14425
- set을 이용하여 in 연산의 시간 복잡도를 줄임
- 시간복잡도: O(N)
- 공간복잡도: O(N)
> [14425] 11.06 안수연

- week9/2003.py
- week9/20310.py
- 문제 번호: 2003
- 왼쪽 포인터(i)를 오른쪽으로 움직일 때(i+1)는 기존의 hap에서 arr[i]를 빼고 오른쪽 포인터(j)를 오른쪽으로 움직일 때(j+1)는 기존의 hap에 arr[j+1]을 더하는 방식으로 시간 복잡도를 줄일 수 있음 (sum을 사용하여 다시 더하는 것보다 효율적)
- 시간복잡도: O(N)
- 공간복잡도: O(N)
- 반복문을 한 번만 사용함
> [2003] 11.08 안수연

- week10/3986.py
- 문제 번호: 3986
- stack 안에 있는 마지막 문자와 동일하면 pop, 동일하지 않으면 append
- stack에 문자가 남아있다면 좋은 문자가 아님
- 시간복잡도: O(N)
- 공간복잡도: O(1)
> [3986] 11.11 안수연

- week10/10994.py
- week9/2003.py
- 문제 번호: 10994
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 4*N -3 이라는 점화식 사용하여 재귀 함수로 풀었음
- 다른 코드들과 비교했을 때 이 코드의 장점은 무엇인가요? 가독성... 그거 말고는 머르겠음
- 코드 리뷰어가 참고해야 할 사항이나 질문이 있다면 작성해 주세요: 좀 더 깔끔 코드도 있던데 아직 그건 이해 못함
> [10994] 11.12 오세영

- week10/10994.py
- week10/1515.py
- 문제 번호: 1515
- 수를 계속 증가시키며 해당하는 수가 있는지 탐색
- 입력받는 수를 deque에 넣고 n의 각 자리수와 비교
- 일치하는 수가 있다면 입력받은 popleft
- 공간복잡도: O(N)
> [1515] 11.13 안수연

- week10/1463.py
- week10/1515.py
- 문제 번호: 1463
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 그 이전 값에서 1을 일단 더해주고 2나 3으로 나눠진다면 dp[2나 3으로 나눈 값] + 1 과 현재의 dp 값중에서 더 작은 값을 dp[i]에 넣어주기 
- 시간복잡도: O(n)
- 공간복잡도: O(n)
- 코드 리뷰어가 참고해야 할 사항이나 질문이 있다면 작성해 주세요: DP규칙 찾기
> [1463] 11.14 오세영

- week11/11399.py
- week11/1904.py
- 문제 번호: 1904
- dp[i] = dp[i-1] + dp[i-2] 를 이용하여 해결
- 시간복잡도: O(N)
- 공간복잡도: O(1)
> [1904] 11.21 안수연

- week11/1904.py
- week11/2559.py
- 문제 번호: 2559
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 누적 합을 구한 후 빼주는 방식을 사용
- 시간복잡도: O(n)
- 공간복잡도: O(n)
- 다른 코드들과 비교했을 때 이 코드의 장점은 무엇인가요? 
- 코드 리뷰어가 참고해야 할 사항이나 질문이 있다면 작성해 주세요: 투 포인터 방식으로 풀어도 됨
> [2559] 11.22 오세영

- week12/2304.py
- week12/2644.py
- 문제 번호: 2304
- 위치 기준 기둥 데이터 정렬
- 왼쪽부터 / 오른쪽부터 각각 한번씩 최대 높이 기둥까지 탐색
- 최대 높이 기둥의 시작과 끝 위치 사이 면적 계산 
- 공간복잡도: O(N)
> [2304] 11.27 안수연

- week12/11726.py
- 문제 번호: 11726
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 점화식 dp[i-1] +dp[i-2] 를 활용해 풀어주기
- 시간복잡도:  O(n)
- 공간복잡도: O(1)
- 코드 리뷰어가 참고해야 할 사항이나 질문이 있다면 작성해 주세요: dp를 잘하는 법. 그게 멀까요?
> [11726] 11.29 오세영

- week12/11726.py
- week12/1181.py
- 문제 번호: 1181
- sort에 다중 조건을 걸어서 해결
- 공간복잡도: O(N)
- 짧음
> [1181] 11.29 안수연

- week12/1181.py
- week13/17266.py
- 문제 번호: 17266
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 리스트 탐색하며 두 조명의 거리를 계산, 짝수, 홀수 나눠서 계산
- 시간복잡도: O(m)
- 공간복잡도: O(m)
> [17266] 12.02 오세영

- week13/17266.py
- week13/20920.py
- 문제 번호: 20920
- 조건을 역순으로 정렬 (사전 순 -> 길이 순 -> 등장한 횟수 순)
- 공간복잡도: O(N)
- 다중 sort
> [20920] 12.03 안수연

- week13/20006.py
- week13/20920.py
- 문제 번호: 20006
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요:  flag를 기준으로 잡고 이미 존재하는 방에 배정되었으면 True, 방 탐색을 모두 마쳤는데도 false라면 이 유저를 기준으로 새로운 방을 생성해야함
- 시간복잡도: O(mlogm)
- 공간복잡도: O(p*m)
> [20006] 오세영

- week13/1927.py
- week13/20006.py
- 문제 번호: 1927
- 파이썬 내장함수인 heapq 이용
- 공간복잡도: O(N)
> [1927] 12.05 안수연

- week13/1927.py
- week13/2667.py
- 문제 번호: 2667
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 다른 bfs와 구조는 똑같은데 단지당 아파트 개수 세는 작업만 추가해서 answer라는 리스트에 저장함
- 공간복잡도: O(n^2)
> [2667] 12.06 오세영

- week13/2667.py
- week14/1780.py
- 문제 번호: 1780
- 재귀 함수를 사용하여 하나라도 숫자가 다른 경우 배열을 9분할
- extend와 set을 사용하는 대신 for i in range (x, x+n)과 for j in range (y, y+n)을 이용하여 arr[i][j]의 값과 동일한지 판별하는 것이 공간을 절약할수있음
> [1780] 12.09 안수연

- week14/1780.py
- week14/2579.py
- 문제 번호: 2579
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요:  dp array에 해당 계단에서 가장 큰 값을 저장해주고 dp와 max이용해서 최댓값 찾아주기
- 시간복잡도: O(n)
- 공간복잡도: O(n)
> [2579] 12.10 오세영

- week14/2346.py
- week14/2805.py
> [2346] 12.12 오세영

- week14/1018.py
- week14/2346.py
- 문제 번호: 1018
- 짝짝/홀홀 이나 짝홀/홀짝에 W와 B가 한 종류씩만 들어가야함
- 짝에 W만 있으면 홀에 B만 있는 식
- 기존 배열에서 체스판으로 만들 8*8 부분을 떼어ㅐ고 짝과 홀에 있는 W와 B의 개수를 셈
- 홀B짝W인 경우와 홀W짝B인 경우 중 덜 바꾸어도 되는 쪽을 반환
- 최종적으로 가장 작은 수를 반환
- 시간복잡도: O(N*M)
- 공간복잡도: O(N*M)
> [1018] 12.13 안수연

- week15/9655.py
- 문제 번호: 9655
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 2의 배수면 sk를 출력 아니면 cy를 출력
- 시간복잡도: O(1)
- 공간복잡도: O(1)
> [9655] 12.17 오세영

- week15/11725.py
- week15/22233.py
- 문제 번호: 22233
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: set을 활용해 검색해야할 내용들을 빼줌
- 시간복잡도: O(n)
- 공간복잡도: O(n)
- 코드 리뷰어가 참고해야 할 사항이나 질문이 있다면 작성해 주세요: 나는 그냥 입력 받는 for문 안에서 결과값을 print해버렸는데 출력할 숫자를 list에 append하고 나중에 그 리스트를 join으로 출력하는게 더 빠르네 왤까
> [22233] 12.19 오세영

- week15/22233.py
- week15/3758.py
- 문제 번호: 3758
- 문제마다 가장 높은 점수만 갱신
- 팀마다 시도 횟수와 마지막 제출 번호를 저장해두었다 마지막에 판별할 때 사용
- 공간복잡도: O(N)
> [3758] 12.20 안수연 greedy

- week16/2607.py
- 문제 번호: 2607
- Counter 함수를 이용해서 각 단어를 이루고 있는 알파벳의 개수를 세고 첫번째 단어의 알파벳과 비교
- value의 합이 1보다 작거나 같으면 비슷한 단어
- 시간복잡도: O(N)
- 공간복잡도: O(N)
> [2607] 12.23 안수연

- week15/3758.py
- week16/17484.py
- 문제 번호: 17484
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: dfs를 이용하여 탐색하였음. 방향이 그 전 방향과 일치하지 않고 지도 안의 범위라면 탐색해준 후 가장 작은 값이라면 low에 저장해줌
- 시간복잡도:  O(m * 3^n)
- 공간복잡도: O(n*m)
> [17484] 12.24 오세영

- week16/17484.py
- week16/2012.py
- 문제 번호: 2012
- 예상 등수를 정렬하고 정렬된 예상 등수에서 실제 등수를 뺀 값의 절대값을 저장
- 공간복잡도: O(N)
> [2012] 12.26 안수연

- week16/2012.py
- week16/2468.py
- 문제 번호: 2468
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 
bfs문제이지만 비가 온 양을 지정한 것이 아니라서 for문을 한 번 더 걸어야 함
여러번 탐색이 필요하기 때문에 visited 배열을 따로 만들어줘서 탐색할 때 사용해줬음
- 공간복잡도: O(n^2)
> [2468] 12.27 오세영

- week17/1697.py
- week17/1931.py
- 문제 번호: 1931
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 끝나는 시간을 기준으로 오름차순 정렬 필요. 만약 끝나는 시간이 같다면 시작하는 시간이 더 빠른 것을 정렬해야함
- 시간복잡도: O(n)
- 공간복잡도: O(n)
> [1931] 01.03 오세영

- week17/1931.py
- week18/11053.py
- 문제 번호: 11053
- dp[i]를 i번째 원소를 마지막 원소로 포함했을 때 리스트의 길이로 정의
- for i in range (1, n), for j in range (0, i)를 이용하여 j로는 i 이전의 수를, i는 1부터 n까지 순회
- 만약 A[j]보다 A[i]가 크다면 dp[i]의 값을 dp[i]와 dp[j]+1 중 큰 값으로 갱신
- 공간복잡도: O(N)
- increase 리스트를 만들고 이를 교체하는게 시간 복잡도가 더 짧음
> [11053] 1.06 안수연

- week18/2108.py
- 문제 번호: 2108 (통계학)
- 1. 산술 평균은 **소수점 이하 첫째 자리에서 반올림**해야 함.
2. 중앙값은 정렬된 리스트에서 가운데 값을 출력.
3. 최빈값은 **여러 개일 경우 두 번째로 작은 값**을 출력해야 함.
4. 범위는 **최댓값 - 최솟값**을 계산.
- 시간복잡도: 
1. 정렬: \(O(N \log N)\)
2. `Counter`를 통한 빈도 계산: \(O(N)\)
3. 최빈값 추출 및 정렬: \(O(M \log M)\) (`M`은 최빈값 후보 개수)
- **총합**: \(O(N \log N)\), \(N\)은 입력 크기
- 공간복잡도:
- 입력 리스트 저장: \(O(N)\)
- 빈도 계산용 딕셔너리: \(O(K)\), \(K\)는 숫자 종류
- 총합: \(O(N + K)\)
- `Counter`를 통한 빈도 계산
> [2108] 01.08 정현주

- week18/1446.py
- week18/2108.py
- 문제 번호: 1446
- 필요하지 않은 지름길은 제거
- d+1 크기만큼 dp를 만들고 dp[i]를 i까지 가는 최단 거리로 설정
- 지름길을 시작점이 빠르고 도착점이 먼 순으로 정렬. 동일하다면 지름길이 짧은 순으로 정렬
- 지름길을 사용해서 도착했을 때와 사용하지 않았을 때 중 더 짧은 쪽을 dp에 저장
- 공간복잡도: O(N)
> [1446] 1.09 안수연

- week18/1940.py
- 문제 번호: 1940
- 리스트를 정렬
- 첫 번째 원소를 s, 마지막 원소를 e로 두고 m보다 합이 작으면 s 증가, m보다 합이 크면 e 감소시키며 검사
- 시간복잡도: O(N)
- 공간복잡도: O(N)
> [1940] 1.10 안수연

- week19/2217.py
- 문제 번호: 2217
- 여러 로프를 사용할 때, 최대 중량은 가장 약한 로프의 중량 × 사용한 로프 개수이므로
- 모든 로프를 포함한 모든 로프를 사용할 때의 최대 중량을 계산
- 계산한 중량 중 가장 큰 값을 갱신
- 공간복잡도: O(N)
- 코드가 간결함
> 2217번 풀이 완료

- week20/10997.py
- 문제 번호: 10997
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 패턴을 찾아서 재귀가 아닌 구현 방식으로 풀어줌 3부분으로 나눠서 각각의 점화식을 적용해줬음
- 공간복잡도: O(1)
- 다른 코드들과 비교했을 때 이 코드의 장점은 무엇인가요? 재귀가 아니라는 점...?
> [10997] 01.22 오세영

- week20/20437.py
- 문제 번호: 20437
- 문자 빈도 계산: 딕셔너리를 이용하여 각 문자가 몇 번 등장하는지 기록
- 슬라이딩 윈도우 이동: 윈도우를 이동하며 K번 등장하는 문자인지 확인
- 조건 만족 시: 최대/최소 길이 갱신
- 시간복잡도: O(N)
- 공간복잡도: O(N)
> [20437] 1.23 정현주

- week20/14501.py
- week20/20437.py
- 문제 번호: 14501
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: dp를 활용해 해결, 이중 for 문 활용
- 공간복잡도: O(n)
> [14501] 01.25 오세영

- week21/1058.py
- week21/11279.py
- 문제 번호: 11279
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 힙정렬은 원래 min정렬인데 최대힙정렬로 바꾸는 방법을 찾아야함. 나는 그냥... 앞에 - 붙여서 사용했음
- 시간복잡도: O(nlogn)
- 공간복잡도: O(n)
> [11279] 02.24 오세영

- week21/1946.py
- 문제 번호: 1946
- 지원자들은 두 가지 등수(서류 등수, 면접 등수)를 가짐
- 서류 등수를 기준으로 오름차순 정렬한 후, 면접 등수가 더 좋은 경우만 선발
- 이전까지 선택된 지원자들 중 최상의 면접 등수(top)를 갱신하며 비교
- 공간복잡도: O(N)
- 그리디 알고리즘 사용
> [1946] 02.05 정현주

- week21/1935.py
- week22/13305.py
- 문제 번호: 13305
- 반복문
- 시간복잡도: O(n)
- 공간복잡도: O(n)
> 2 개 문제 풀이 완료

- week23/5567.py
- 문제 번호: 5567
- set을 활용하여 상근이의 친구와 친구의 친구를 더함 (중복 방지)
- 1과 연결된 친구를 set에 add하고 그 친구들과 연결된 친구들을 set에 add
- 시간복잡도: O(N)
- 공간복잡도: O(N)
> [5567] 02.17 안수연

- week22/30804.py
- week23/2910.py
- 문제 번호: 2910
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 그냥 count와 등장 순서에 맞춰 해주면 된다고 생각했는데 그게 아니라 빈도 수도 한번 정렬이 필요했음 그래서 dictionary에 숫자 = [빈도, 순서] 를 저장하고 람다로 한번 더 정렬해준 다음에 최종 list를 만들어줬음
- 시간복잡도: O(nlogn)
- 공간복잡도: O(n)
> [2910] 02.18 오세영

- week23/12919.py
- 문제 번호: 12919
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: S가 T가 될 수 있는지 판단하는 것보다 T가 S가 될 수 있는지 판단하는게 재귀에서 효율적임
- 시간복잡도: O(n)
- 공간복잡도: O(n)
> [12919] 02.19 오세영

- week23/1459.py
- week23/1912.py
- 문제 번호: 1912
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: dp[i]는 numbers의 i번째 숫자를 포함하는 가장 큰 연속합 그래서 max 연산 비교 해주기
- 시간복잡도: O(n)
- 공간복잡도: O(n)
> [1912] 02.21 오세영

- week23/1912.py
- week24/3190.py
- 문제 번호: 3190
- board를 이용하여 뱀이 존재하는 부분을 True, 나머지를 False로 둠
- 시간초를 증가시키며 뱀을 이동
- 사과를 먹으면 사과를 제거하고 먹지 못했다면 꼬리를 이동
- 이때 deque를 이용하여 꼬리의 뒷부분 위치를 확인
> [3190] 02.24 안수연

- week24/14499.py
- 문제 번호: 14499
- 주사위가 돌아가는 로직만 구현하면 나머지는 쉬움
- 주사위가 돌아갈 때 북쪽으로 굴린다면 동서는 변함이 없고 위 아래 북 남 방향의 면만 바뀌도록 고치면 됨 
- 시간복잡도: O(N)
- 공간복잡도: O(N)
> [14499] 02.25 안수연

- week24/14500.py
- 문제 번호: 14500
- ㅏ 모양을 제외한 모든 모양은 dfs를 이용해서 가장 큰 값을 탐색
- ㅏ 모양은 예외처리 (1. 네 방향이 모두 배열 안에 있는 경우 2. 세 방향만 배열 안에 있는 경우)
> [14500] 02.27 안수연

- week24/10844.py
- week24/3190.py
- 문제 번호: 10844
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: dp, 이중 for문을 돌려주는데 왜냐면 2-8까지는 양 옆으로 올 수 있는 수들이 있기 때문에 이중 for문 돌려줌 계단수의 개념이 너무 익숙치 않아서 이해하는데 오래 걸림
- 시간복잡도: O(n)
- 공간복잡도: O(n)
> [10844] 02.27 오세영

- week25/14719.py
- 문제 번호: 14719
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요:  for i 를 기준으로 왼쪽, 오른쪽으로 배열을 나눈 뒤에 왼쪽의 최댓값, 오른쪽의 최댓값 중에서 작은걸 구한 다음에 현재 i번째의 값을 빼주면 빗물의 높이가 나옴
- 시간복잡도: O(w^2)
- 공간복잡도: O(w)
> [14719] 03.07 오세영

- week25/11000.py
- week25/14719.py
- 문제 번호: 11000
- 시간 시작 빠른 순으로 정렬
- 만약 가장 빠른 끝나는 시간보다 시작 시간이 이르다면 강의실 추가
- 그게 아니라면 가장 빠른 끝나는 시간으로 그 다음 강의가 끝나는 시간을 갱신
- 이때 강의실마다 강의가 끝나는 시간 배열이 계속 정렬되어 있어야 하는데, heap을 이용하면 O(N log N)의 시간 복잡도로 해결 가능
- 공간복잡도: O(N)
> [11000] 03.07 안수연

- week26/4485.py
- 문제 번호: 4485
- 이 코드가 문제를 어떻게 해결했는지 설명해 주세요: 상하좌우 모두 탐색하는 bfs 구현이 필요
- 공간복잡도: O(n^2)
> [4485] 03.10 오세영

- week26/13549.py
- week26/2156.py
- 문제 번호: 2156
- 자료구조/알고리즘: 동적 계획법 (DP)
- 연속 세 잔을 마실 수 없다는 조건을 만족하면서 최대로 마실 수 있는 포도주의 양을 구하는 문제
- 점화식 설정이 핵심:
- `dp[i] = max(dp[i-1], dp[i-2] + wines[i], dp[i-3] + wines[i-1] + wines[i])`
- i번째 포도주를 마시는 경우와 마시지 않는 경우를 고려
- 시간복잡도: O(N)  
- 한 번의 for문으로 해결 가능
- 공간복잡도: O(N)  
- DP 배열을 사용하여 저장
-------------- 
- 문제 번호: 13549
- 자료구조/알고리즘:
- 다익스트라 (Dijkstra) 알고리즘
- 우선순위 큐 (heapq)
- 문제를 이해하는 데 중요한 부분:
- 이동 방법에 따라 가중치가 다름
- 순간이동(`X * 2`)은 시간이 증가하지 않음(비용 0)
- 걸어서 이동(`X + 1` or `X - 1`)은 시간이 1초 추가됨
- 다익스트라 알고리즘을 활용하여 최소 시간을 구함
- 시간복잡도: **O(N log N)** (우선순위 큐를 사용하는 다익스트라)
- 공간복잡도: **O(N)** (거리 배열과 우선순위 큐의 크기)
> [2156, 13549] 03.17 정현주

- week26/1027.py
- week26/13549.py
- week26/2156.py
- week27/1253.py
- week27/20055.py
- 문제 번호: 20055
- deque와 boolean 배열을 이용해서 로봇이 있는지 없는지 확인
- 로봇이 n에 도달하면 사라진다는 것을 명심할 것
- deque의 rotate를 사용해서 레일을 돌리고 로봇을 이동시키며 내구도 감소시킴
- 시간복잡도: O(N)
- 공간복잡도: O(N)
> [20055] 03.17 안수연

- week27/13144.py
- week27/15686.py
- week27/5972.py
- week28/16928.py
- week28/7682.py
- 문제 번호: 13144
- part라는 리스트를 만들어서 arr[l]를 추가
- 만약 r이 리스트 안에 있다면 l을 증가시키면서 리스트 안의 r을 제거
- 이때 추가되는 수열의 개수는 리스트의 크기와 동일
- 시간복잡도: O(N)
- 공간복잡도: O(N)
> [13144] 03.21 안수연

- week29/22251.py
- week29/2668.py
- 문제 번호: 2668
- 자료구조/알고리즘: DFS(깊이 우선 탐색), 사이클 탐색
- 숫자들을 연결하여 그래프를 형성하고, 사이클을 찾아 그 숫자들만 선택해야 함
- DFS를 사용하여 탐색 중 사이클을 감지하면 결과 집합에 포함
- 시간복잡도: O(N) (각 숫자에 대해 DFS 탐색 수행)
- 공간복잡도: O(N) (재귀 호출 스택과 방문 여부 저장을 위한 공간)
---------------
- 문제 번호: 22251
- 자료구조/알고리즘: 비트마스크, 브루트포스(완전 탐색)
- 7-세그먼트 디스플레이의 점등 패턴을 이용해 숫자를 비교해야 함
- 현재 층과 1부터 N까지 모든 숫자를 비교하며 자리별 점등 차이를 계산
- 변경할 수 있는 최대 P개의 세그먼트 내에서 변환 가능한 숫자를 찾기
- 시간복잡도: O(N × K) (각 숫자에 대해 K자리 비교 수행)
- 공간복잡도: O(1) (고정된 크기의 배열과 변수만 사용)
> [2668, 22251] 04.01 정현주

- week29/7490.py
- 문제 번호: 7490
- 지금까지의 계산식, 다음에 올 숫자를 받아서 만약 다음에 올 숫자가 n보다 커지면 종료
- 지금까지의 계산식을 계산한 결과가 0이면 cf를 출력
- 아스키 코드 순서에 맞게 ' ', +, - 순서로 계산
- 시간복잡도: O(3^N)
- 공간복잡도: O(N)
> [7490] 04.02 안수연

- week29/16234.py
- week29/2631.py
- 문제 번호: 16234
- bfs를 이용해서 차이가 l 이상 r 이하인 나라를 찾음
- union에 나라가 추가되면 bfs가 True를 return
- 모든 bfs가 False라면 movement가 False가 되고 while문이 종료됨
- 탐색 조건에 제한을 두지 않으면 시간 초과
- 시간복잡도: O(N^4)
> [16234] 04.04 안수연
